version: '2'
services:
  db:
    build:
      context: ./MySQL
    env_file:
      - prod.env
    environment:
      - MYSQLDUMP_OPTIONS=--quick --single-transaction
    container_name: go_db
    ports:
      - "3306:3306"
    tty: true
    restart: always
    volumes:
      - ./MySQL/mysql_init:/docker-entrypoint-initdb.d
      - ./MySQL/mysql_data:/var/lib/mysql
      - ./mysqldump/mysqldump.sh:/mysqldump.sh
      - ./mysqldump/dumpfiles:/dumpfiles
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake --lower_case_table_names=1
  app:
    build:
      context: ./Go
      dockerfile: Dockerfile.prod
    volumes:
      - "./Go:/go/src/app"
    container_name: go_app
    env_file:
      - prod.env
    ports:
      - "8080:8080"
    tty: true
    restart: always
    depends_on:
      - db
  https-portal:
    image: steveltn/https-portal:1
    container_name: https_portal
    ports:
      - "80:80"
      - "443:443"
    tty: true
    restart: always
    volumes:
      - ./Certs/:/var/lib/https-portal/
    environment:
      DOMAINS: 'shijimi.work => www.shijimi.work, www.shijimi.work -> http://app:8080'
      STAGE: "production"
      # FORCE_RENEW: 'true'
    links:
      - app
  metabase:
    container_name: go_metabase
    image: metabase/metabase:v0.33.7.1
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_HOST=go_db
    env_file:
      - prod.env
    volumes:
      - "./metabase/metabase-data:/metabase-data"
    ports:
      - "30001:3000"
    tty: true
    restart: always
    depends_on:
    - db
  # phpmyadmin:
  #   container_name: go_phpmyadmin
  #   image: phpmyadmin/phpmyadmin:4.8
  #   environment:
  #   - PMA_ARBITRARY=1
  #   - PMA_HOSTS=db
  #   ports:
  #   - 30002:80
  #   volumes:
  #     - ./phpmyadmin/sessions:/sessions
  #   tty: true
  #   depends_on:
  #     - db