version: '2'
services:
  db:
    build:
      context: ./MySQL
    env_file:
      - dev.env
    container_name: go_db
    ports:
      - "3306:3306"
    tty: true
    restart: always
    volumes:
      - ./MySQL/mysql_init:/docker-entrypoint-initdb.d
      - ./MySQL/mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --skip-character-set-client-handshake --lower_case_table_names=1
  app:
    build:
      context: ./Go
      dockerfile: Dockerfile.dev
    volumes:
      - "./Go:/go/src/app"
    container_name: go_app
    env_file:
      - dev.env
    ports:
      - "8080:8080"
    tty: true
    restart: always
    depends_on:
    - db
  https-portal:
    image: steveltn/https-portal:1
    container_name: https_portal
    ports:
      - "8000:80"
      - "4430:443"
    tty: true
    restart: always
    volumes:
      - ./Certs/:/var/lib/https-portal/
    environment:
      DOMAINS: '192.168.2.174 -> http://app:8080'
      STAGE: "local"
      # FORCE_RENEW: 'true'
    links:
      - app
  metabase:
    container_name: go_metabase
    image: metabase/metabase:v0.33.7.1
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_PORT=3306
      - MB_DB_HOST=go_db
    env_file:
      - dev.env
    volumes:
      - "./metabase/metabase-data:/metabase-data"
    ports:
      - "30001:3000"
    tty: true
    restart: always
    depends_on:
    - db
  phpmyadmin:
    container_name: go_phpmyadmin
    image: phpmyadmin/phpmyadmin:4.8
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=db
    ports:
    - 30002:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    tty: true
    depends_on:
      - db