version: '2'
services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doramaba_db
      MYSQL_USER: doramaba
      MYSQL_PASSWORD: doramaba_pass
      TZ: "Asia/Tokyo"
    container_name: go_db
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - ./MySQL/mysql_init:/docker-entrypoint-initdb.d
      - ./MySQL/mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
  app:
    build:
      context: ./Go
    volumes:
      - "./Go:/go/src/app"
    container_name: go_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
