version: '2'
services:
  db:
    build:
      context: ./MySQL
    env_file:
      - ./MySQL/mysql.env
    container_name: go_db
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - ./MySQL/mysql_init:/docker-entrypoint-initdb.d
      - ./MySQL/mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
  app:
    build:
      context: ./Go
      dockerfile: Dockerfile.dev
    volumes:
      - "./Go:/go/src/app"
    container_name: go_app
    env_file:
      - ./Go/conf/go.env
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
  phpmyadmin:
    container_name: go_phpmyadmin
    image: phpmyadmin/phpmyadmin:4.8
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=db
    ports:
    - 8000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    tty: true
    depends_on:
      - db